### ISSUE TITLE
Resetting ItemStackServerRule rules causes exception spam

### ISSUE THREAD

**Issue by SuperNeon4ik** [Noxcrew/noxesium#100]
### Scope of the issue
Server-side paper implementation at `:paper`

### Issue
When running `RemoteServerRule<ItemStack>#reset()` the updater that runs every tick fails to reset the serverRule _(ex.: `HAND_ITEM_OVERRIDE`)_. Seems that the fail occurs because `net.minecraft.world.item.ItemStack.CODEC` refuses to encode `minecraft:air` for some reason, which is the default value.

### Exception
```log
[22:58:29 WARN]: [NoxesiumUtils] Task #3 for NoxesiumUtils v2.0.0 generated an exception
io.netty.handler.codec.EncoderException: Failed to encode: Value must be within range [1;99]: 0; Item must not be minecraft:air 0 minecraft:air
        at net.minecraft.network.FriendlyByteBuf.lambda$writeJsonWithCodec$3(FriendlyByteBuf.java:133) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at net.minecraft.network.FriendlyByteBuf.writeJsonWithCodec(FriendlyByteBuf.java:132) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at net.minecraft.network.FriendlyByteBuf.writeJsonWithCodec(FriendlyByteBuf.java:126) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.rule.ItemStackServerRule.write(RemoteServerRule.kt:116) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.rule.ItemStackServerRule.write(RemoteServerRule.kt:109) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager$updateServerRules$2$1.invoke(NoxesiumManager.kt:193) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager$updateServerRules$2$1.invoke(NoxesiumManager.kt:192) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.v2.NoxesiumListenerV2$createPacket$1.invoke(NoxesiumListenerV2.kt:69) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.v2.NoxesiumListenerV2$createPacket$1.invoke(NoxesiumListenerV2.kt:62) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.BaseNoxesiumListenerKt.createPayloadPacket(BaseNoxesiumListener.kt:97) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.BaseNoxesiumListenerKt.createPayloadPacket$default(BaseNoxesiumListener.kt:89) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.v2.NoxesiumListenerV2.createPacket(NoxesiumListenerV2.kt:62) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.createPacket(NoxesiumManager.kt:134) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.sendPacket(NoxesiumManager.kt:143) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.updateServerRules(NoxesiumManager.kt:188) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.register$lambda$0(NoxesiumManager.kt:74) ~[NoxesiumUtils-2.0.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:475) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1724) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:473) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1302) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-98-9b1ee0d]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

[Трансляція_20240924_230258.webm](https://github.com/user-attachments/assets/18c39bbd-99c1-4f19-880b-b36e838d4a8a)

### System information
**Java:** Java 21 (OpenJDK 64-Bit Server VM 21.0.4+7) 
**Host:** Linux 6.10.10-arch1-1 (amd64)

**MC Client:** 1.21
**Noxesium (mod)**: 2.3.1 (found in 2.3.0)
**Noxesium:paper (dependency):** 2.3.1-dev (found in 2.3.0-dev)

**MC Server:** `Paper version 1.21.1-98-master@9b1ee0d` **(affected; found on)**
**MC Server:** `git-Paper-497 (MC: 1.20.4)` **(unaffected)**
**MC Server:** `Paper version 1.20.6-150-ver/1.20.6@e61b73f` **(different issue/couldn't test)**:
```log
java.lang.NoSuchMethodError: 'net.minecraft.resources.ResourceLocation net.minecraft.resources.ResourceLocation.parse(java.lang.String)'
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.BaseNoxesiumListenerKt.createPayloadPacket(BaseNoxesiumListener.kt:95) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.BaseNoxesiumListenerKt.createPayloadPacket$default(BaseNoxesiumListener.kt:89) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.v2.NoxesiumListenerV2.createPacket(NoxesiumListenerV2.kt:62) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.createPacket(NoxesiumManager.kt:134) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.sendPacket(NoxesiumManager.kt:143) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.updateServerRules(NoxesiumManager.kt:188) ~[NoxesiumUtils-2.0.0.jar:?]
        at NoxesiumUtils-2.0.0.jar/com.noxcrew.noxesium.paper.api.NoxesiumManager.register$lambda$0(NoxesiumManager.kt:74) ~[NoxesiumUtils-2.0.0.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-150-e61b73f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by Aeltumn** [comment]
Will be fixed in the next release of Noxesium, starting in protocol version 11. This will break usage of any item stack rules on older versions.
