### ISSUE TITLE
Experimental Optimizations Causes Game Crash

### ISSUE THREAD

**Issue by p1nkcosmo** [Noxcrew/noxesium#118]
When I enable "Experimental Optimizations" I get an instant crash with Exit Code 6. I can restart my game and go through the menus but cannot join a server or load a world. I'm on the latest version of fabric and have tried removing all other mods besides Noxesium and Fabric API. I am on 1.21.4 and am using a M1 Mac Mini and the vanilla launcher. Let me know if there's any other information I can provide :)

**Comment by Aeltumn** [comment]
Can you provide the crash log for this? You can find this in the logs folder of your minecraft game folder.

**Comment by p1nkcosmo** [comment]
Here's my game log after recreating this issue. Let me know if you need anything else
[latestlog.txt](https://github.com/user-attachments/files/18189709/latestlog.txt)

**Comment by Aeltumn** [comment]
That log doesn't seem to have any crash in it, do you have any files in the crash-reports folder?

**Comment by p1nkcosmo** [comment]
Huh, it doesn't seem to be generating a crash report. Only message is Exit Code 6 in the launcher.

**Comment by p1nkcosmo** [comment]
I tried repeating this with minecraft game output open and this information seems to be related to the crash?

16:07:29.711
launcher
main
������)�� native method: Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL44C.nglBufferStorage(Native Method)
	at org.lwjgl.opengl.GL44C.glBufferStorage(GL44C.java:171)
	at org.lwjgl.opengl.GL44.glBufferStorage(GL44.java:169)
	at com.noxcrew.noxesium.feature.ui.render.ElementBuffer.resize(ElementBuffer.java:181)
	at com.noxcrew.noxesium.feature.ui.render.ElementBuffer.bind(ElementBuffer.java:136)
	at com.noxcrew.noxesium.feature.ui.render.DynamicElement.update(DynamicElement.java:276)
	at com.noxcrew.noxesium.feature.ui.render.NoxesiumUiRenderState.render(NoxesiumUiRenderState.java:108)
	at com.noxcrew.noxesium.feature.ui.layer.NoxesiumLayeredDraw.render(NoxesiumLayeredDraw.java:92)
	at net.minecraft.class_9080.wrapMethod$baa000$noxesium$render(class_9080.java:549)
	at net.minecraft.class_9080.method_55809(class_9080.java)
	at net.minecraft.class_329.method_1753(class_329.java:234)
	at net.minecraft.class_757.method_3192(class_757.java:533)
	at net.minecraft.class_310.method_1523(class_310.java:1341)
	at net.minecraft.class_310.method_1514(class_310.java:922)
	at net.minecraft.client.main.Main.main(Main.java:267)
	at java.lang.invoke.LambdaForm$DMH/0x00000008002e8000.invokeStaticInit(java.base@21.0.3/LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$MH/0x00000008002d0c00.invokeExact_MT(java.base@21.0.3/LambdaForm$MH)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
16:07:29.711
monitor
Process Monitor
Process crashed with exit code 6

**Comment by Aeltumn** [comment]
I see, it seems like OpenGL 4.4 isn't available, I thought it was required to use Minecraft in recent versions. I will probably need to auto-disable it when using an older version.

**Comment by p1nkcosmo** [comment]
Yeah, MacOS uses an old version of OpenGL (4.1) and Apple says they won't update it and it's now "deprecated". Weird

**Comment by Aeltumn** [comment]
Will be resolved in 2.6.0.
