### ISSUE TITLE
Player head components sometimes cause an NPE when split with `ComponentRenderUtils.wrapComponents()` 

### ISSUE THREAD

**Issue by lucyydotp** [Noxcrew/noxesium#14]
I'm still trying to determine the pattern - it's very sporadic and only seems to be players with incomplete texture futures. 

For example,
```
ComponentRenderUtils.wrapComponents(playerHeadComponent, 100, minecraft.font)
```
_sometimes_ throws
```
 java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "string" is null
	at net.minecraft.client.StringSplitter.method_27487(StringSplitter.java:418)
	at net.minecraft.network.chat.FormattedText$3.visit(FormattedText.java:51)
	at net.minecraft.network.chat.FormattedText$4.visit(FormattedText.java:77)
	at net.minecraft.client.StringSplitter.splitLines(StringSplitter.java:417)
	at net.minecraft.client.gui.components.ComponentRenderUtils.wrapComponents(ComponentRenderUtils.java:32)
```

`method_27487` is the formatted text visitor callback at the top of `StringSplitter;splitLines(FormattedText, int, Style, BiConsumer<FormattedText, Boolean)`.

**Comment by lucyydotp** [comment]
Never mind turns out this is just my code being broken
