### ISSUE TITLE
noxesium -1.20.4 Crash

### ISSUE THREAD

**Issue by HazeWorksOnFiveMServer** [Noxcrew/noxesium#51]
MODs :
	- alloy_forgery 2.1.3+1.20.3
	- amplified_nether 1.2.4
	- antighost 1.20.4-fabric0.91.2-1.1.5
	   \-- crowdin-translate 1.4+1.19.3
	- architectury 11.1.17
	- auditory 0.0.6-1.20.4
	- badoptimizations 2.1.0
	- bedrodium 0.2.3
	- betterdeserttemples 1.20.4-Fabric-3.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterdungeons 1.20.4-Fabric-4.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterendisland 1.20.4-Fabric-2.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterfortresses 1.20.4-Fabric-2.4.2
	   \-- org_reflections_reflections 0.10.2
	- betterjungletemples 1.20.4-Fabric-2.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterloot 1.0.0+mc1.20.4
	- bettermaps 0.5.2
	- bettermineshafts 1.20.4-Fabric-4.4.1
	   \-- org_reflections_reflections 0.10.2
	- betteroceanmonuments 1.20.4-Fabric-3.4.1
	   \-- org_reflections_reflections 0.10.2
	- betterstrongholds 1.20.4-Fabric-4.4.1
	   \-- org_reflections_reflections 0.10.2
	- bettertridents 20.4.0
	   |-- cardinal-components-base 5.4.0
	   \-- cardinal-components-entity 5.4.0
	- betterwitchhuts 1.20.4-Fabric-3.4.1
	   \-- org_reflections_reflections 0.10.2
	- bigendcitiesmod 1.20.4-1.0.4
	- c2me 0.2.0+alpha.11.58
	   |-- c2me-base 0.2.0+alpha.11.58
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.58
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.58
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.58
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.58
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.58
	   |-- c2me-notickvd 0.2.0+alpha.11.58
	   |-- c2me-opts-allocs 0.2.0+alpha.11.58
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.58
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.58
	   |-- c2me-opts-math 0.2.0+alpha.11.58
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.58
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.58
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.58
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.58
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.58
	   |-- c2me-server-utils 0.2.0+alpha.11.58
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.58
	   |-- c2me-threading-lighting 0.2.0+alpha.11.58
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.58
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- cameraoverhaul 1.4.0-fabric-universal
	- centered-crosshair 1.0.6
	- chat_heads 0.10.32
	- chatanimation 1.0.5
	- chatpatches 204.6.4
	- clean-debug 0.4.4
	- cloth-config 13.0.121
	   \-- cloth-basic-math 0.6.1
	- collective 7.40
	- collisionfix 1.0.1
	- combatnouveau 20.4.5
	- completeconfig 2.5.3
	   |-- completeconfig-base 2.5.3
	   |-- completeconfig-gui-cloth 2.5.3
	   \-- completeconfig-gui-yacl 2.5.3
	- crash-pipe 0.1.0
	- ctov 3.4.2
	- cutthrough 20.4.2
	- deathfinder 20.4.1
	- debugify 1.20.4+1.0
	- detailab 2.6.3+1.20.4-fabric
	- diagonalwalls 20.4.0
	   \-- diagonalblocks 20.4.2
	- ding 1.4.1
	- easyanvils 20.4.3
	- easymagic 20.4.0
	- easyshulkerboxes 20.4.5
	   \-- iteminteractions 20.4.4
	- echochest 20.4.1
	- effectdescriptions 20.4.0
	- emuno 1.1.1
	- enchantinginfuser 20.4.0
	- endermanoverhaul 1.1.8
	- endrem 5.2.4
	- entity_model_features 1.3
	- entity_texture_features 5.2.3
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.3.1
	- euphonium 1.0.1+1.20
	   \-- folk_sisby_kaleido-config 0.1.1+1.1.0-beta.3
	- experimentalperformance 0.1.1
	   |-- io_github_classgraph_classgraph 4.8.162
	   \-- org_openjdk_jol_jol-core 0.17
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabric-language-kotlin 1.10.19+kotlin.1.9.23
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.23
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.23
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.23.2
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.8.0
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.5.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.3
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.3
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.3
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- fallingleaves 1.15.4
	- faster-random 3.0.2
	- fastipping 1.0.1
	- ferritecore 6.0.3
	- firstperson 2.3.4
	- forgeconfigapiport 20.4.3
	   |-- com_electronwill_night-config_core 3.6.6
	   \-- com_electronwill_night-config_toml 3.6.6
	- geckolib 4.4.4
	   \-- com_eliotlash_mclib_mclib 20
	- hopobettermineshaft 1.2.1
	- hopobetterruinedportal 1.3.9
	- hopobetterunderwaterruins 1.1.5
	- horsearmorstandmod 1.0.2-1.20.4
	- idletweaks 1.0.8
	- immediatelyfast 1.2.10+1.20.4
	   \-- net_lenni0451_reflect 1.3.2
	- indium 1.0.30+mc1.20.4
	- iris 1.6.17
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- jade 13.3.1
	- java 17
	- krypton 0.2.6
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- lambdynlights 2.3.4+1.20.4
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.3+1.20.2
	- leavemybarsalone 20.4.1
	- leavesbegone 20.4.1
	- lithium 0.12.1
	- lithostitched 1.1.5
	- loading-window 1.0.0
	- make_bubbles_pop 0.2.0-fabric
	- memoryleakfix 1.1.5
	- midnightlib 1.5.3
	- minecraft 1.20.4
	- modelfix 1.14
	- modernfix 5.15.0+mc1.20.4
	- modmenu 9.0.0
	- moreculling 1.20.4-0.22.1
	   |-- conditional-mixin 0.3.2
	   \-- mixinsquared 0.1.1
	- morecullingextra 1.1-1.20.1
	- mru 0.4.0+1.20.4
	- mythicmetals 0.19.5+1.20.4
	   |-- additionalentityattributes 1.6.0+1.20.4
	   |-- cardinal-components-base 5.4.0
	   |-- cardinal-components-entity 5.4.0
	   \-- common-protection-api 1.0.0
	- mythicmetals_decorations 0.6.1+1.20.3
	- mythicupgrades 2.4.2+mc1.20.4
	- narrus_yeetus 1.1.0
	- nerb 0.3
	- netherchested 20.4.1
	   \-- limitlesscontainers 20.4.0
	- noisium 1.0.2+mc1.20.x
	- notenoughanimations 1.7.1
	- noxesium 1.2.0+669ccb7
	   \-- com_noxcrew_noxesium_api_ 1.2.0+669ccb7
	- nullscape 1.2.4
	- nvidium 0.2.6-beta
	- optigui 2.3.0-alpha.2
	   |-- org_apache_commons_commons-text 1.11.0
	   \-- org_ini4j_ini4j 0.5.4
	- owo 0.12.5+1.20.3
	- packetfixer 1.2.4
	- pickupnotifier 20.4.2
	- presencefootsteps 1.11.2
	   \-- kirin 1.17.0+1.20.4
	- puzzleslib 20.4.41
	- radio 1.20.4-1.0.0
	- raised 3.1.3
	- reeses-sodium-options 1.7.2+mc1.20.4-build.102
	- resourcefulconfig 2.4.5
	- resourcefullib 2.4.10
	   |-- com_teamresourceful_bytecodecs 1.0.2
	   \-- com_teamresourceful_yabn 1.0.3
	- simpleradio 2.2.4
	- skinlayers3d 1.6.2
	- smoothmenu 1.1.0
	- smoothscrollingrefurbished 1.1.2
	- sodium 0.5.8+mc1.20.4
	- sodium-extra 0.5.4+mc1.20.4-build.116
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- sound_physics_remastered 1.20.4-1.3.1
	- sounds 0.6.0+1.20.4
	- stylisheffects 20.4.2
	- swordblockingmechanics 20.4.1
	- tectonic 2.2.1
	- threadtweak 1.20.4-0.1.2
	- toomanyplayers 1.20.4-1.1.5
	   \-- libgui 9.2.2+1.20.2
	        |-- jankson 6.0.0+j1.2.3
	        |    \-- blue_endless_jankson 1.2.3
	        \-- libninepatch 1.2.0
	- travelerstitles 1.20.4-Fabric-4.4.0
	   \-- org_reflections_reflections 0.10.2
	- triqueapi 1.1.1+mc1.20.4
	- universalbonemeal 20.4.2
	- vcinteraction 1.20.4-1.0.6
	   \-- polymer-registry-sync-manipulator 0.7.1+1.20.4
	- villagespawnpoint 4.2
	- visuality 0.7.3+1.20.4
	- visualworkbench 20.4.1
	- vmp 0.2.0+beta.7.138
	   \-- com_ibm_async_asyncutil 0.1.0
	- voicechat 1.20.4-2.5.9
	- wardentools 2.4.0+mc1.20.4
	- wwoo 2.0.1
	- yet_another_config_lib_v3 3.3.2+1.20.4
	   |-- com_twelvemonkeys_common_common-image 3.10.0
	   |-- com_twelvemonkeys_common_common-io 3.10.0
	   |-- com_twelvemonkeys_common_common-lang 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yungsapi 1.20.4-Fabric-4.4.2
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- yungsextras 1.20.4-Fabric-4.4.0
	   \-- org_reflections_reflections 0.10.2

Crash :

[15:05:11] [main/ERROR]: Mixin apply for mod noxesium failed noxesium.mixins.json:component.TranslatableContentsMixin from mod noxesium -> net.minecraft.class_2588: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method method_54239 in noxesium.mixins.json:component.TranslatableContentsMixin from mod noxesium cannot reduce visibiliy of PUBLIC target method
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_54239 in noxesium.mixins.json:component.TranslatableContentsMixin from mod noxesium cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:479) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:452) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2561.method_43471(class_2561.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_155.<clinit>(class_155.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:63) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
[15:05:11] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_155.<clinit>(class_155.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:63) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2588 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2561.method_43471(class_2561.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_155.<clinit>(class_155.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:63) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2561.method_43471(class_2561.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_155.<clinit>(class_155.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:63) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [noxesium.mixins.json:component.TranslatableContentsMixin from mod noxesium] from phase [DEFAULT] in config [noxesium.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2561.method_43471(class_2561.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_155.<clinit>(class_155.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:63) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PRIVATE @Overwrite method method_54239 in noxesium.mixins.json:component.TranslatableContentsMixin from mod noxesium cannot reduce visibiliy of PUBLIC target method
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.conformVisibility(MixinPreProcessorStandard.java:479) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:452) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5+mixin.0.8.5.jar:0.12.5+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.minecraft.class_2561.method_43471(class_2561.java:226) ~[client-intermediary.jar:?]
	at net.minecraft.class_2156.<clinit>(class_2156.java:24) ~[client-intermediary.jar:?]
	at net.minecraft.class_155.<clinit>(class_155.java:266) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:63) ~[1.20.4-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	... 2 more

**Comment by Aeltumn** [comment]
This should be fixed in the next release.
