### ISSUE TITLE
NullPointerException: Localplayer is null

### ISSUE THREAD

**Issue by lrsvmb** [Noxcrew/noxesium#97]
I am getting a null pointer exception every time I try to join a multiplayer server.

This is only happening with `v2.3.0`, `v2.2.0` works. Full logs are here:

[disconnect-2024-09-08_16.26.25-client.txt](https://github.com/user-attachments/files/16922582/disconnect-2024-09-08_16.26.25-client.txt)

Or as code block:

```
---- Minecraft Network Protocol Error Report ----
// Could be worse, I guess

Time: 2024-09-08 16:22:03
Description: Packet handling error

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_746.method_37908()" because "localplayer" is null
	at net.minecraft.class_634.handler$cfi000$noxesium$handleRespawn(class_634.java:7563)
	at net.minecraft.class_634.method_11117(class_634.java)
	at net.minecraft.class_2724.method_11782(class_2724.java:44)
	at net.minecraft.class_2724.method_11054(class_2724.java:9)
	at net.minecraft.class_2535.method_10759(class_2535.java:208)
	at net.minecraft.class_2535.method_10770(class_2535.java:193)
	at net.minecraft.class_2535.channelRead0(class_2535.java:69)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Netty Client IO #3
Stacktrace:
	at net.minecraft.class_634.handler$cfi000$noxesium$handleRespawn(class_634.java:7563)
	at net.minecraft.class_634.method_11117(class_634.java)

-- Connection --
Details:
	Protocol: play
	Flow: CLIENTBOUND
	Server type: OTHER
	Server brand: ~~NULL~~
Stacktrace:
	at net.minecraft.class_2547.method_55622(class_2547.java:33)
	at net.minecraft.class_2600.method_59803(class_2600.java:62)
	at net.minecraft.class_8673.method_60882(class_8673.java:136)
	at net.minecraft.class_8673.method_60881(class_8673.java:127)
	at net.minecraft.class_2535.exceptionCaught(class_2535.java:161)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:447)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202)
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Unknown Source)

-- Wynntils --
Details:
	Loaded Overlays: 
		Shaman Totem Timer
		Corrupted Bar
		Arrow Shield Tracker
		Custom Player List Overlay
		Powder Special Bar
		Minimap
		Ophanim Bar
		Info Box 2
		Daily Objective
		Status Overlay
		Spell Cast Overlay
		Info Box 8
		Territory
		Info Box 9
		Info Box 4
		Info Box 6
		Info Box 1
		Mob Totem Timer
		Focus Bar
		Lootrun Missions
		Aura Timer
		Guild Objective
		Content Tracker
		Lootrun Beacon Count
		Info Box 7
		Awakened Bar
		Info Box 3
		Token Bars
		Info Box 5
		Party Members
		Volley Timer
		NPC Dialogue
		Combat Experience
		Lootrun Task Name
		Bomb Bell Overlay
		Game Notifications
		Annihilation Sun
		Shaman Mask Overlay
	In Development: No
	Loaded Features: 
		Lootrun
		Bomb Bell Relay
		Chat Coordinates
		Chat Item
		Chat Mentions
		Chat Tabs
		Death Coordinates
		Dialogue Button Override
		Transcribe Sent Messages
		Message Filter
		Abbreviate Mob Health
		Tracked Content
		Custom Lootrun Beacons
		Block Inventory Casting
		Health Potion Blocker
		Horse Mounting
		Low Health Indicator
		Mythic Chest Blocker
		Mythic Box Item Scaling
		Prevent Trades & Duels
		Quick Spell Cast
		Major ID Range Visualizer
		Shaman Totem Tracking
		Spell Cast Vignette Render
		Token Tracker Bell
		Add Command Expansion
		Command Aliases
		Custom Command Keybinds
		Filter Admin Commands
		Wybel Sounds
		Wynntils Cosmetics
		Container Search Highlight
		Disable Recipe Book
		Durability Arc
		Emerald Pouch Fill Arc
		Emerald Pouch Hotkey
		Extended Item Count
		Guild Bank Hotkey
		Highlight Duplicate Cosmetics
		Ingredient Pouch Keybind
		Inventory Emerald Count
		Favorite Items
		Item Highlights
		Item Lock
		Item Screenshot
		Item Text Overlays
		Lootrun Chest Text
		Personal Storage Utilities
		Unidentified Item Icon
		Beacon Beam
		Guild Map
		Map
		Minimaps
		Waypoint Distance
		Annihilation Sun Overlay
		Arrow Shield Tracking
		Bomb Bell
		Combat Experience Overlays
		Tracked Content Overlay
		Custom Bars
		Custom Player List
		Game Bars
		Game Updates
		Info Boxes
		Lootrun Overlays
		Mob Totem Tracking
		NPC Dialogues
		Objectives
		Hades Party Overlays
		Powder Specials Bars
		Shaman Masks
		Shaman Totem Timer Overlay
		Spell Cast Message Overlay
		Statuses
		Token Tracker Overlay
		Tower Effect Overlay
		Auto Join Parties
		Nametag Rendering
		Gear Viewer
		Hades
		Party Management Screen
		Transparent Player Ghost
		Ability Refreshes
		Blacksmith Messages
		Info Message Filter
		Pouch Messages
		Territory Messages
		Item Compare
		Item Guess
		Item Statistics Info
		Tooltip Fitting
		Hide Irrelevant Tooltip Info
		Market Auto Open Chat
		Trade Market Bulk Sell Buttons
		Market Price Conversion
		Trade Market Price Match Buttons
		Bulk Buy
		Container Scroll
		Cosmetics Player Preview
		Crafting Profession Progress Bar
		Custom Character Selection
		Custom Loading Screen
		Custom Seaskipper Screen
		Custom Trade Market Result Screen
		Lobby Uptime
		Profession Highlight
		Wynncraft Button
		Wynntils Pause Screen
		Wynntils Content Book
		Auto Apply Resource Pack
		Gammabright Keybind
		Per Character Guild Contribution
		Silencer
		Skill Point Loadouts
		Transcribe Received Messages
		XP Gain Messages
		Beta Warning
		Changelog
		Custom Wynntils Command
		Data Crowd Sourcing
		Fix Packet Bugs
		Telemetry
		Updates
		Weekly Config Backup
		Discord Rich Presence
		Extended Season Leaderboard
		Mythic Found
		Send Territory Defenses

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 1191246312 bytes (1136 MiB) / 2407530496 bytes (2296 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: 13th Gen Intel(R) Core(TM) i5-13600KF
	Identifier: Intel64 Family 6 Model 183 Stepping 1
	Microarchitecture: Raptor Lake
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 14
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 4090
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 24564.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.6081
	Memory slot #0 capacity (MiB): 16384.00
	Memory slot #0 clockSpeed (GHz): 6.40
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MiB): 16384.00
	Memory slot #1 clockSpeed (GHz): 6.40
	Memory slot #1 type: Unknown
	Virtual memory max (MiB): 42320.14
	Virtual memory used (MiB): 25193.97
	Swap memory total (MiB): 9728.00
	Swap memory used (MiB): 135.11
	Space in storage for jna.tmpdir (MiB): available: 107488.19, total: 476166.69
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 107488.19, total: 476166.69
	Space in storage for io.netty.native.workdir (MiB): available: 107488.19, total: 476166.69
	Space in storage for java.io.tmpdir (MiB): available: 107488.19, total: 476166.69
	Space in storage for workdir (MiB): available: 107488.19, total: 476166.69
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16384M
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.0.5
		appleskin: AppleSkin 3.0.5+mc1.21
		betterf3: BetterF3 11.0.1
		capes: Capes 1.5.4+1.21
		cloth-config: Cloth Config v15 15.0.130
			cloth-basic-math: cloth-basic-math 0.6.1
		continuity: Continuity 3.0.0-beta.5+1.21
		controlling: Controlling 18.0.4
		creativecore: CreativeCore 2.12.9
			net_neoforged_bus: bus 7.2.0
		cubes-without-borders: Cubes Without Borders 2.1.1+1.21
		cullleaves: Cull Leaves 3.4.0
			midnightlib: MidnightLib 1.5.7
		distanthorizons: Distant Horizons 2.2.1-a
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.24+b559734490
		eatinganimationid: Eating Animation 1.21+1.9.72
		entityculling: EntityCulling 1.7.0
		fabric-api: Fabric API 0.102.0+1.21
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.68+b5597344d1
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.29+5bd9f1bcd1
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a7d1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8cd1
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a7d1
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8cd1
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366fd1
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd9d1
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b3d1
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.16+b5597344d1
			fabric-convention-tags-v1: Fabric Convention Tags 2.0.19+7f945d5bd1
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.5.0+c5e2b5c6d1
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a7d1
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.27+6a6dfa19d1
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.16+16c4ae25d1
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b99d1
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.12+6fc22b99d1
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.12+ba9dae06d1
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd9d1
			fabric-item-api-v1: Fabric Item API (v1) 11.0.0+afdfc921d1
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.4+78017270d1
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b3d1
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.12+6c1df360d1
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.14+3f89f5a5d1
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.2+3f89f5a5d1
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8cd1
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6bd1
			fabric-networking-api-v1: Fabric Networking API (v1) 4.2.2+60c3209bd1
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.0+a551f7a4d1
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8cd1
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.12+65089712d1
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.1.2+60c3209bd1
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49cd1
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49cd1
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b3d1
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2ed1
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+b5597344d1
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b3d1
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd0d1
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b1d1
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.0+56599129d1
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.86+b5597344d1
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8cd1
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.1.16+3dccd343d1
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.1.0+176f9036d1
		fabric-language-kotlin: Fabric Language Kotlin 1.12.1+kotlin.2.0.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.25.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.1
			org_jetbrains_kotlinx_kotlinx-io-bytestring-jvm: kotlinx-io-bytestring-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-io-core-jvm: kotlinx-io-core-jvm 0.5.3
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.7.1
		fabricloader: Fabric Loader 0.16.2
			mixinextras: MixinExtras 0.4.1
		fallingleaves: Falling Leaves 1.16.2
		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		iris: Iris 1.8.0-beta.3+mc1.21.1
			io_github_douira_glsl-transformer: glsl-transformer 2.0.1
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1
		java: OpenJDK 64-Bit Server VM 21
		konkrete: Konkrete 1.9.9
		lithium: Lithium 0.13.0
		minecraft: Minecraft 1.21
		modernfix: ModernFix 5.19.1+mc1.21
		modmenu: Mod Menu 11.0.2
		morechathistory: More Chat History 1.3.1
		noxesium: Noxesium 2.3.0+3bbfed9
			com_noxcrew_noxesium_api: api 2.3.0+3bbfed9
			org_khelekore_prtree: prtree 1.5
		placeholder-api: Placeholder API 2.4.1+1.21
		reeses-sodium-options: Reese's Sodium Options 1.8.0-beta.2+mc1.21.1
		searchables: Searchables 1.0.5
		skinlayers3d: 3d-Skin-Layers 1.6.7
		sodium: Sodium 0.6.0-beta.1+mc1.21
		sodium-extra: Sodium Extra 0.6.0-beta.1+mc1.21.1
			com_lodborg_interval-tree: interval-tree 1.0.0
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.6
		stutterfix: StutterFix mc1.21-0.2.3
		videotape: Video Tape 1.0.0
		wakes: Wakes 0.3.0+1.21.1
			blue_endless_jankson: jankson 1.2.2
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		waveycapes: WaveyCapes 1.4.9
		wynntils: Wynntils 2.1.3
		wynnventory: Wynnventory 0.6.2
		wynnvp: Voices of wynn 1.8.2
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.21
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Loaded Shaderpack: ComplementaryUnbound_r5.2.2.zip
		Profile: Custom (+21 options changed by user)
```

**Comment by Aeltumn** [comment]
I've made a fix for this for the next update, however I cannot recreate the issue myself. I am wondering if there's some other mod you are running that is causing this indirectly. It is still Noxesium crashing so I will fix it, but it might only happen in combination with another mod.

**Comment by LordOfTheWeebs** [comment]
> I've made a fix for this for the next update, however I cannot recreate the issue myself. I am wondering if there's some other mod you are running that is causing this indirectly. It is still Noxesium crashing so I will fix it, but it might only happen in combination with another mod.

If it helps, I just ran a clean instance with only Fabric API and Noxesium, and I have the same problem with specifically Wynncraft. I tried connecting to Hypixel and XCraft Survival and had no issue.
[latest.log](https://github.com/user-attachments/files/16984347/latest.log)
[disconnect-2024-09-12_14.53.05-client.txt](https://github.com/user-attachments/files/16984349/disconnect-2024-09-12_14.53.05-client.txt)

**Comment by VRXDev2** [comment]
Having same issue, private server - there is a limbo server on it (limbo is an empty world for things like AFK, or fallback in case the server crashes to not lose players). When I get connected to a normal server from the limbo, I get kicked with the error from the above post.
Limbo plugin: https://www.spigotmc.org/resources/nanolimboplugin.105297/
